version: "3"

services:
  app:
    image: streamlit-docker
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./app:/usr/app/src/
